markdown:               kramdown
highlighter:            rouge
permalink:              /:categories/:title.html
relative_permalinks:    false
title:                  'Bits'
description:            'Random posts written by <a href="https://mdminhazulhaque.com">Md. Minhazul Haque</a>'
url:                    'http://bits.minhazulhaque.com'
paginate:               20
gems:
    - jekyll-sitemap
    - jekyll-paginate
