markdown:               kramdown
highlighter:            rouge
permalink:              /:categories/:title.html
relative_permalinks:    false
title:                  'Bits'
description:            'Random posts written by <a href="https://mdminhazulhaque.io">Md. Minhazul Haque</a>'
url:                    'https://bits.minhazulhaque.io'
paginate:               20
gems:
    - jekyll-sitemap
    - jekyll-paginate
