markdown:               kramdown
highlighter:            rouge
permalink:              /:categories/:title.html
relative_permalinks:    false
title:                  'Bits'
description:            'Random posts written by <a href="https://mdminhazulhaque.io">Md. Minhazul Haque</a>'
url:                    'https://bits.mdminhazulhaque.io'
paginate:               20
plugins:
    - jekyll-feed
    - jekyll-sass-converter
    - jekyll-sitemap
    - jekyll-paginate
sass:
    style: compressed
exclude:
    - poole
    - hyde
    - submodules.sh
