markdown:               kramdown
highlighter:            rouge
permalink:              /:categories/:title.html
relative_permalinks:    false
title:                  'Bits'
description:            'Random posts written by <a href="https://mdminhazulhaque.io">Minhaz</a>'
url:                    'https://bits.mdminhazulhaque.io'
paginate:               20
destination:            ./docs
plugins:
    - jekyll-feed
    - jekyll-sass-converter
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-archives
sass:
    style: compressed
exclude:
    - poole
    - hyde
    - build.sh
    - .sass-cache
    - README.md
jekyll-archives:
    enabled:
        - categories
    layout: category
    permalinks:
        category: /:name/index.html
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
